Prerquisites:
#1. We need AWS Collections to perform actions on AWS
# > ansible-galaxy collection install amazon.aws --force
#2. We need boto3 for Ansible to talk to AWS API
# > sudo apt install python3-boto3

---
- hosts: localhost   #We are runing on same machine
  connection: local   #We are running playbook on same machine
  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "ansible-instance"
      # key_name: "prod-ssh-key"
      # vpc_subnet_id: subnet-013744e41e8088axx
      instance_type: t2.micro
      security_group: default
      region: us-east-1
      AWS_Access_Key: "{{ec2_access_key}}"  # From vault as defined
      AWS_Secret_Key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: ami-04b70fa74e45c3917
      tags:
        Environment: Testing
